article/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='homepage'),
    path('contact/', views.contact, name='contact'),
    
]

feedback/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('feedback/', views.feedback, name='feedback'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='homepage'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('', include('feedback.urls')),
    path('', include('home.urls')),
]

article/models.py
from django.db import models
from django.shortcuts import reverse
import datetime
from django.utils.text import slugify
class Topic(models.Model):
    name = models.CharField(unique=True, max_length=37)

    def __str__(self):
        return self.name


ARTICLE_TYPE_CHOICE = [
    ('MR', 'Must Read'),
    ('RS', 'Read Slowly'),
    ('FF', 'Fun Fact'),
]

class Article(models.Model):
    title = models.CharField(max_length=121, default='Title')
    slug = models.SlugField(unique=True)
    published = models.DateField(default=datetime.date.today)
    kind_article = models.CharField(max_length=2, default='MR', choices=ARTICLE_TYPE_CHOICE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article,self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("article-detail", kwargs={'id': self.pk, 'slug': self.slug})
    

exam/models.py
from django.db import models


LEVEL_CHOICES = [
    ('0', 'Novice'),
    ('1', 'Advanced Beginner'),  
    ('2', 'Competent'),
    ('3', 'Proficient'),
    ('4', 'Expert'),
]
class Level(models.Model):
    level = models.CharField(max_length=1, primary_key=True, default='0', choices=LEVEL_CHOICES)

    def __str__(self):
        return self.level



ANSWER_CHOICES = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D')
]
class Answer(models.Model):
    answer = models.CharField(max_length=1, primary_key=True, default='A', choices=ANSWER_CHOICES)

    def __str__(self):
        return self.answer

class Question(models.Model):
    detail = models.TextField(default="question empty")
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE)

feedback/models.py
from django.db import models

# Create your models here.
class FeedBack(models.Model):
    name = models.CharField(default='user', max_length=121)
    email = models.EmailField()
    message = models.TextField()

home/models.py
from django.db import models

# Create your models here.

feedback/forms.py
from django import forms

class FeedBack(forms.Form):
    """
        Form feedback with admin website
    """
    name = forms.CharField(label='name', max_length=25)
    email = forms.EmailField(label='email', max_length=121)
    message = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return f"{self.name}({self.email})"        

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView
from django.template import RequestContext
from .models import Article


def get_redirected(queryset_or_class, lookups, validators):
    '''
        Call get_object_or_404 and conditionally build redirect URL
    '''
    obj = get_object_or_404(queryset_or_class, **lookups)
    for key, value in validators.items():
        if value != getattr(obj,key):
            return obj.get_absolute_url()
    return None

class ArticleView(DetailView):
    model = Article
    template_name = 'article_detail.html'


class ArticleListView(ListView):
    model = Article
    pass

def article_detail(request, id, slug):
    article_url = get_redirected(Article, {'pk': id}, {'slug': slug})
    if article_url:
        return redirect(article_url)
    
    else:
        #404 error
        pass

exam/views.py
from django.shortcuts import render

# Create your views here.

feedback/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import FeedBack


def feedback(request):
    
    if request.method == 'POST':
        form = forms.FeedBack(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print("User feedback: ")
            print(f"{data['name'], data['email'], data['message']}")
            feedback = FeedBack(name=data['name'], email=data['email'], message=data['message'])
            feedback.save()
            
            return render(request, template_name='thankyou.html')
    
    return render(request, template_name='404error.html')

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'homepage.html', {})


def about(request):
    return render(request, 'about.html', {})

article/templates/grammer.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Funny Vocab</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="css/animate.min.css">
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/font-awesome.min.css">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href='css/style.css'>
		<script src="js/jquery.js"></script>
		<script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.singlePageNav.min.js"></script>
		<script src="js/typed.js"></script>
		<script src="js/wow.min.js"></script>
		<script src="js/custom.js"></script>
	</head>
	<body id="top">

		<!-- start preloader -->
		<div class="preloader">
			<div class="sk-spinner sk-spinner-wave">
     	 		<div class="sk-rect1"></div>
       			<div class="sk-rect2"></div>
       			<div class="sk-rect3"></div>
      	 		<div class="sk-rect4"></div>
      			<div class="sk-rect5"></div>
     		</div>
    	</div>
    	<!-- end preloader -->

        <!-- start header -->
        <header>
           <div class="top_header">
            <div class="container">
                <div>
                    <div class="col-sm-4 col-xs-12">
                      <p><em class="fa fa-phone"></em><span> Phone</span>123 456 789</p>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">Funnyvocab@gmail.com</a></p>
                    </div>
                    <div class="col-md-5 col-sm-4 col-xs-12">
                        <ul class="social-icon">
                            <li><span>Meet us on</span></li>
                            <li><a href="#" class="fa fa-facebook"></a></li>
                            <li><a href="#" class="fa fa-twitter"></a></li>
                            <li><a href="#" class="fa fa-instagram"></a></li>
                            <li><a href="#" class="fa fa-youtube"></a></li>
                        </ul>
                </div>
                  <div class="col-md-5 col-sm-4 col-xs-12" style="text-align: right";>
                <div class="text">
                    <input type="search" placeholder="Bạn muốn tìm kiếm" style="margin-top: 10px;width: 250px;height: 30px; border: 2px solid #A9A9A9;border-radius: 12px;">
                    <button class="btn btn-danger" style="font-size: 12px" ><em class="fa fa-search" aria-hidden="true"></em> Search</button>
				</div>
			</div>
            </div>
            </div>
        </header>
        <!-- end header -->

    	<!-- start navigation -->
		<nav class="navbar navbar-default templatemo-nav" role="navigation">
			<div class="container">
				<div class="navbar-header">
				
					<a href="#" class="navbar-brand">Funny Vocab</a>
				</div>
				<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav ">
						<li  class="nav-item active"><a class="nav-link"  href="home.html">HOME</a></li>
						<li class="nav-item"><a  class="nav-link" href="grammer.html">GRAMMER</a></li>
						<li class="nav-item"><a class="nav-link" href="listening.html">LISTENING</a></li>
						<li class="nav-item"><a class="nav-link"  href="reading.html">READING</a></li>
						<li class="nav-item"><a class="nav-link" href="writing.html">WRITING</a></li>
						<li class="nav-item"><a class="nav-link"  href="#contact">CONTACT</a></li>
					</ul>
				</div>
			</div>
		</nav>
</body>
</html>

article/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Funny Vocab</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="{% static 'homepage/css/animate.min.css'%}">
		<link rel="stylesheet" href="{% static  'homepage/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static  'homepage/css/font-awesome.min.css'%}">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
		<script src="{% static  'js/jquery.js'%}"></script>
		<script src="{% static  'js/bootstrap.min.js'%}"></script>
        <script src="{% static  'js/jquery.singlePageNav.min.js'%}"></script>
		<script src="{% static  'js/typed.js'%}"></script>
		<script src="{% static  'js/wow.min.js'%}"></script>
		<script src="{% static  'js/custom.js'%}"></script>
	</head>
	<body id="top">

		<!-- start preloader -->
		<div class="preloader">
			<div class="sk-spinner sk-spinner-wave">
     	 		<div class="sk-rect1"></div>
       			<div class="sk-rect2"></div>
       			<div class="sk-rect3"></div>
      	 		<div class="sk-rect4"></div>
      			<div class="sk-rect5"></div>
     		</div>
    	</div>
    	<!-- end preloader -->

        <!-- start header -->
        <header>
           <div class="top_header">
            <div class="container">
                <div>
                    <div class="col-sm-4 col-xs-12">
                      <p><em class="fa fa-phone"></em><span> Phone</span>123 456 789</p>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">Funnyvocab@gmail.com</a></p>
                    </div>
                    <div class="col-md-5 col-sm-4 col-xs-12">
                        <ul class="social-icon">
                            <li><span>Meet us on</span></li>
                            <li><a href="#" class="fa fa-facebook"></a></li>
                            <li><a href="#" class="fa fa-twitter"></a></li>
                            <li><a href="#" class="fa fa-instagram"></a></li>
                            <li><a href="#" class="fa fa-youtube"></a></li>
                        </ul>
                </div>
                  <div class="col-md-5 col-sm-4 col-xs-12" style="text-align: right";>
                <div class="text">
                    <input type="search" placeholder="Bạn muốn tìm kiếm" style="margin-top: 10px;width: 250px;height: 30px; border: 2px solid #A9A9A9;border-radius: 12px;">
                    <button class="btn btn-danger" style="font-size: 12px" ><em class="fa fa-search" aria-hidden="true"></em> Search</button>
				</div>
			</div>
            </div>
            </div>
        </header>
        <!-- end header -->

    	<!-- start navigation -->
		<nav class="navbar navbar-default templatemo-nav" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon icon-bar"></span>
						<span class="icon icon-bar"></span>
						<span class="icon icon-bar"></span>
					</button>
					<a href="{% url 'homepage' %}" class="navbar-brand">Funny Vocab</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li class="active"><a  href="index.html">HOME</a></li>
						<li><a href="grammer.html">GRAMMER</a></li>
						<li><a href="listening.html">LISTENING</a></li>
						<li><a  href="reading.html">READING</a></li>
						<li><a href="writing.html">WRITING</a></li>
						<li><a  href="#contact">CONTACT</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- end navigation -->
		<img src="{% static  'homepage/images/learning e.webp' %}" width="1350px" height="500px">
		<!-- start home -->
    	<section id="home">
    				<div class="container">
    			<div class="row">
    				<div class="col-md-offset-2 col-md-8">
    					<h1 class="wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">WELCOME TO <span>FUNNY VOCAB</span></h1>
    					<div class="element">
                            <div class="sub-element">If you are not willing to learn, no one can help you.</div>
                            <div class="sub-element">If you are determined to learn, no one can stop you.</div>
                            <div class="sub-element">Never stop learning because life never stop teaching!</div>
                        </div>
    					<a data-scroll href="#about" class="btn btn-default wow fadeInUp" data-wow-offset="50" data-wow-delay="0.6s">GET STARTED</a>
    				</div>
				</div>
    		</div>
    	</section>
				<!-- end home -->
				<!-- start about-->
				<section id="about">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
    					<h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">WE ARE <span>FUNNY VOCAB</span></h2>
    				</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.6s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left">
									<i class="fa fa-question-circle"></i>
								</div>
								<h3 class="media-heading">WHY ARE YOU LEARNING ENGLISH?</h3>
							</div>
							<div class="media-body">
								<p>English is currently the most widely used language.<br/>
								English offers many career opportunities.<br/>
								Acquire rich knowledge from the outside.<br/>
								English helps you perfect yourself.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInUp" data-wow-offset="50" data-wow-delay="0.9s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left">
									<i class="fa fa-book"></i>
								</div>
								<h3 class="media-heading">HOW TO LEARN ENGLISH?</h3>
							</div>
							<div class="media-body">
								<p>Learning vocabulary by topic.<br/>
								Talking a lot.<br/>
								Learning English through short stories.<br/>
								Practice writing notes.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left"><em class="fa fa-comment-o"></em></div>
								<h3 class="media-heading">FREE SUPPORT</h3>
							</div>
							<div class="media-body">
								<p>When studying with friends, you will discuss lessons more freely. As a result, you gain a new approach from your classmate.<br/>
								Please contact with us!</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- end about -->
    	
    		<!-- start contact -->
    	<section id="contact">
    		<div class="container">
    			<div class="row">
    				<div class="col-md-12">
    					<h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">CONTACT <span>FUNNY VOCAB TEAM</span></h2>
    				</div>
    				<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.9s">
						<form method="post"> {% csrf_token %}
    						<label>NAME</label>
    						<input name="fullname" type="text" class="form-control" id="fullname" maxlength="25" required>
   						  	
                            <label>EMAIL</label>
    						<input name="email" type="email" class="form-control" id="email" maxlength="121" required>
   						  	
                            <label>MESSAGE</label>
    						<textarea name="message" rows="4" class="form-control" id="message"></textarea>
    						
                            <input type="submit" class="form-control">
    					</form>
    				</div>
    				<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
    					<address>
    						<p class="address-title">OUR ADDRESS</p>
    						<span>Ho Chi Minh City.</span>
    						<p><i class="fa fa-phone"></i> 123 456 789</p>
    						<p><i class="fa fa-envelope-o"></i> Funnyvocab@gmail.com</p>
    						<p><i class="fa fa-map-marker"></i> Ho Chi Minh City</p>
    					</address>
    					<ul class="social-icon">
    						<li><h4>WE ARE SOCIAL</h4></li>
    						<li><a href="#" class="fa fa-facebook"></a></li>
    						<li><a href="#" class="fa fa-twitter"></a></li>
    						<li><a href="#" class="fa fa-youtube"></a></li>
    					</ul>
    				</div>
    			</div>
    		</div>
    	</section>
    	<!-- end contact -->

    
</body>
</html>

feedback/templates/404error.html
{% load static %}
<!doctype html>
<html lang="en">
		
<head>
<meta charset="utf-8">
<title>Funny Vocab</title>
			
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.singlePageNav.min.js'%}"></script>
        <link rel="stylesheet" href="{%static 'css/style tks.css'%}">
</head>
<body>
        <p>Co cai  quan dui</p>
</body>

</html>

feedback/templates/thankyou.html
{% load static %}
<!doctype html>
<html lang="en">
		
<head>
<meta charset="utf-8">
<title>Funny Vocab</title>
			
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.singlePageNav.min.js'%}"></script>
        <link rel="stylesheet" href="css/style tks.css">
</head>
<body>
			<img src="{% static 'images/tksyou1.jpg'%}" width="1365px" height="300px">
					
					<div class="container">
   					
    		
    					<h1 style="color:whitesmoke; background-color: lightskyblue; text-align:center">We will reply you soon! </h1>
    		</div>	
    		<img src="{% static 'images/mail-icon-ios-7.png' %}" width="500" height="250" class="cangiua">
</body>

</html>

home/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Funny Vocab</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="{% static 'homepage/css/animate.min.css'%}">
		<link rel="stylesheet" href="{% static  'homepage/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static  'homepage/css/font-awesome.min.css'%}">
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
		<script src="{% static  'js/jquery.js'%}"></script>
		<script src="{% static  'js/bootstrap.min.js'%}"></script>
		<script src="{% static  'js/typed.js'%}"></script>
		<script src="{% static  'js/wow.min.js'%}"></script>
		<script src="{% static  'js/custom.js'%}"></script>
	</head>
	<body id="top">

		<!-- start preloader -->
		<div class="preloader">
			<div class="sk-spinner sk-spinner-wave">
     	 		<div class="sk-rect1"></div>
       			<div class="sk-rect2"></div>
       			<div class="sk-rect3"></div>
      	 		<div class="sk-rect4"></div>
      			<div class="sk-rect5"></div>
     		</div>
    	</div>
    	<!-- end preloader -->

        <!-- start header -->
        <header>
           <div class="top_header">
            <div class="container">
                <div>
                    <div class="col-sm-4 col-xs-12">
                      <p><em class="fa fa-phone"></em><span> Phone</span>123 456 789</p>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">Funnyvocab@gmail.com</a></p>
                    </div>
                    <div class="col-md-5 col-sm-4 col-xs-12">
                        <ul class="social-icon">
                            <li><span>Meet us on</span></li>
                            <li><a href="#" class="fa fa-facebook"></a></li>
                            <li><a href="#" class="fa fa-twitter"></a></li>
                            <li><a href="#" class="fa fa-instagram"></a></li>
                            <li><a href="#" class="fa fa-youtube"></a></li>
                        </ul>
                </div>
                  <div class="col-md-5 col-sm-4 col-xs-12" style="text-align: right";>
                <div class="text">
                    <input type="search" placeholder="Bạn muốn tìm kiếm" style="margin-top: 10px;width: 250px;height: 30px; border: 2px solid #A9A9A9;border-radius: 12px;">
                    <button class="btn btn-danger" style="font-size: 12px" ><em class="fa fa-search" aria-hidden="true"></em> Search</button>
				</div>
			</div>
            </div>
            </div>
        </header>
        <!-- end header -->

    	<!-- start navigation -->
		<nav class="navbar navbar-default templatemo-nav" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon icon-bar"></span>
						<span class="icon icon-bar"></span>
						<span class="icon icon-bar"></span>
					</button>
					<a href="{% url 'homepage' %}" class="navbar-brand">Funny Vocab</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li class="active"><a  href="index.html">HOME</a></li>
						<li><a href="grammer.html">GRAMMER</a></li>
						<li><a href="listening.html">LISTENING</a></li>
						<li><a  href="reading.html">READING</a></li>
						<li><a href="writing.html">WRITING</a></li>
						<li><a  href="#contact">CONTACT</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- end navigation -->
		<img src="{% static  'homepage/images/learning e.webp' %}" width="1350px" height="500px">
		<!-- start home -->
    	<section id="home">
    				<div class="container">
    			<div class="row">
    				<div class="col-md-offset-2 col-md-8">
    					<h1 class="wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">WELCOME TO <span>FUNNY VOCAB</span></h1>
    					<div class="element">
                            <div class="sub-element">If you are not willing to learn, no one can help you.</div>
                            <div class="sub-element">If you are determined to learn, no one can stop you.</div>
                            <div class="sub-element">Never stop learning because life never stop teaching!</div>
                        </div>
    					<a data-scroll href="#about" class="btn btn-default wow fadeInUp" data-wow-offset="50" data-wow-delay="0.6s">GET STARTED</a>
    				</div>
				</div>
    		</div>
    	</section>
				<!-- end home -->
				<!-- start about-->
				<section id="about">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
    					<h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">WE ARE <span>FUNNY VOCAB</span></h2>
    				</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.6s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left">
									<i class="fa fa-question-circle"></i>
								</div>
								<h3 class="media-heading">WHY ARE YOU LEARNING ENGLISH?</h3>
							</div>
							<div class="media-body">
								<p>English is currently the most widely used language.<br/>
								English offers many career opportunities.<br/>
								Acquire rich knowledge from the outside.<br/>
								English helps you perfect yourself.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInUp" data-wow-offset="50" data-wow-delay="0.9s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left">
									<i class="fa fa-book"></i>
								</div>
								<h3 class="media-heading">HOW TO LEARN ENGLISH?</h3>
							</div>
							<div class="media-body">
								<p>Learning vocabulary by topic.<br/>
								Talking a lot.<br/>
								Learning English through short stories.<br/>
								Practice writing notes.</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
						<div class="media">
							<div class="media-heading-wrapper">
								<div class="media-object pull-left"><em class="fa fa-comment-o"></em></div>
								<h3 class="media-heading">FREE SUPPORT</h3>
							</div>
							<div class="media-body">
								<p>When studying with friends, you will discuss lessons more freely. As a result, you gain a new approach from your classmate.<br/>
								Please contact with us!</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- end about -->
    	
    		<!-- start contact -->
    	<section id="contact">
    		<div class="container">
    			<div class="row">
    				<div class="col-md-12">
    					<h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">CONTACT <span>FUNNY VOCAB TEAM</span></h2>
    				</div>
    				<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.9s">
						<form method="post" action={% url 'feedback' %}> 
						    {% csrf_token %}
							<label for="id_name">Name</label> 
							<input type="text" class="form-control" name="name" maxlength="25" required id="id_name">

							<label for="id_email">Email</label> 
							<input type="email" class="form-control" name="email" maxlength="121" required id="id_email">
							
							<label for="id_message">Message</label> 
							<textarea name="message" rows="4" class="form-control" required id="id_message"></textarea>
    										
                            <input type="submit" class="form-control"> 
    					</form>
    				</div>
    				<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
    					<address>
    						<p class="address-title">OUR ADDRESS</p>
    						<span>Ho Chi Minh City.</span>
    						<p><i class="fa fa-phone"></i> 123 456 789</p>
    						<p><i class="fa fa-envelope-o"></i> Funnyvocab@gmail.com</p>
    						<p><i class="fa fa-map-marker"></i> Ho Chi Minh City</p>
    					</address>
    					<ul class="social-icon">
    						<li><h4>WE ARE SOCIAL</h4></li>
    						<li><a href="#" class="fa fa-facebook"></a></li>
    						<li><a href="#" class="fa fa-twitter"></a></li>
    						<li><a href="#" class="fa fa-youtube"></a></li>
    					</ul>
    				</div>
    			</div>
    		</div>
    	</section>
    	<!-- end contact -->

    
</body>
</html>